# Generated by Django 4.2.9 on 2026-07-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-created_at', '-date']},
        ),
        migrations.RemoveField(
            model_name='workout',
            name='split',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='Untitled Workout', max_length=120),
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs'), ('upper', 'Upper'), ('lower', 'Lower'), ('full', 'Full Body'), ('custom', 'Custom')], default='full', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
