# Generated by Django 4.2.9 on 2026-07-13 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_workout_options_remove_workout_split_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'ordering': ['workout', 'order']},
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
