# Generated by Django 4.2.9 on 2026-07-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_dietlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietlog',
            name='meal5',
            field=models.BooleanField(default=False),
        ),
    ]
